--รายการยา homc ที่ยังไม่ได้จับคู่กับ invs
SELECT DISTINCT [CODE_HOS],[MED_HOS]
FROM [DISPENSED_TEMP]
WHERE WORKING_CODE IS NULL


SELECT (DEPT_ID) ,RTRIM([DEPT_NAME])AS DEPT_NAME
FROM[DEPT_ID]
WHERE HIDE = 'N' AND HOSP_TYPE='1'--AND(DEPT_ID +' : '+DEPT_NAME LIKE '%" + txtDEPT_NEW.Text + "%')
ORDER BY DEPT_NAME

SELECT DEPT_ID,DEPT_NAME FROM dbo.DEPT_ID WHERE HOSP_TYPE='1' AND INV_TYPE='3' AND DEPT_TYPE='3'